### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by ITTV-tools** [treban/pimatic-raspbee#1]
Hi,
if the API Key was entered in the gui. It gets replaced with "[object Object]" (after restart) and I can't discover my devices.

**Comment by treban** [comment]
i will check this.
Can you generate a new key?: 
1: delete the key line in the plugin config 
2: start pimatic
3: unlock the gateway 
4: start a device discovery
5: a new key will generated and saved with a pimatic restart in the config file

**Comment by ITTV-tools** [comment]
If I try that, it discovers my devices and after I added it to my room, it says offline. (Maybe because the gateway is locked again.)

**Comment by ITTV-tools** [comment]
Thats the error message I get: error [pimatic-raspbee]: { [Error: getaddrinfo ENOTFOUND mia mia:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'mia',
  host: 'mia',
  port: '443',
  __trace: 'Error: From connect\n    at Socket.connect (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:55:29)\n    at Agent.exports.connect.exports.createConnection (net.js:68:26)\n    at Agent.createSocket (_http_agent.js:180:16)\n    at Agent.addRequest (_http_agent.js:149:23)\n    at new ClientRequest (_http_client.js:142:16)\n    at Object.exports.request (http.js:31:10)\n    at WebSocket.initAsClient (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/WebSocket.js:708:21)\n    at new WebSocket (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/WebSocket.js:79:18)\n    at /home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:22:17\n    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)' }

**Comment by treban** [comment]
thx for the logfile. i have a bug in the code. I will fix it this evening and publish a new version.

**Comment by treban** [comment]
new version published. 0.0.3
the problem should be gone

**Comment by ITTV-tools** [comment]
Its working. Thank you.
