### ISSUE TITLE
Deconz and Pimatic are not in sync

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-raspbee#16]
Hello Treban,
i have an issue where the deconz webinterface changes the status of the different sensors nearly immeditly, but on the pimatic side there is no change or it is very slow. Is this a problem on the websocket from the deconz software or on pimatic side?

two Screenshots from the both frontends. First one shot was the deconz and after that pimatic.

http://prntscr.com/jmt6dy

http://prntscr.com/jmt67z

**Comment by scobby** [comment]
hmmm now it works. We should monitor that.

**Comment by sweebee** [comment]
I found the following problem:

when scanning for lights in deconz, somehow pimatic loses the web socket connection, I have to restart pimatic to get it working again.

**Comment by mat1990dj** [comment]
I'm also having issues with pimatic and deconz sync
deconz informs new updates and they dont appear on pimatic

**Comment by treban** [comment]
I will create a check if the web socket connection is still available and healthy.

**Comment by treban** [comment]
version 0.0.8 should fix this problem. The websocket has now a keep-alive and reconnect function.

**Comment by scobby** [comment]
think this is fixed
