### ISSUE TITLE
Aqara wall switches can't be controlled only viewed

### ISSUE THREAD

**Issue by mat1990dj** [treban/pimatic-raspbee#19]
My aqara wall switches are correctly connected to deconz
When I do auto discovery they appear on pimatic but with no default device type.
I've tried them all, using the type for lights, the on off status is updated in pimatic when I press the phisical button, but if I change from UI the phisical switch does not change status (is still off ie)

Edit: I can't use the plugin and I'm using shellswitches to call directly the api :(

**Comment by treban** [comment]
I'll check that out. Can you post the output of the log file during a discovery? In debug mode there should be a json output of the wall plug. I don't have wall plugs.

**Comment by mat1990dj** [comment]
Sorry I don't mean the wall plug, I'm talking about the switch to control lights
Edit: I'll post the logs

**Comment by mat1990dj** [comment]
I'm not getting a JSON for the wall switches
I only get the following:
20:16:42.358 [pimatic] info: Starting device discovery for 20000ms.
20:16:44.645 [pimatic] info: Device discovered: pimatic-raspbee : Sensor: lumi.ctrl_neutral1 - lumi.ctrl_neutral1
20:16:44.655 [pimatic] info: Device discovered: pimatic-raspbee : Sensor: lumi.ctrl_neutral1 (2) - lumi.ctrl_neutral1
20:16:44.660 [pimatic] info: Device discovered: pimatic-raspbee : Sensor: lumi.ctrl_neutral1 - lumi.ctrl_neutral1
20:16:44.662 [pimatic] info: Device discovered: pimatic-raspbee : Sensor: lumi.ctrl_neutral1 (2) - lumi.ctrl_neutral1
20:16:44.665 [pimatic] info: Device discovered: pimatic-raspbee : Light: Light 2 - null
20:16:44.667 [pimatic] info: Device discovered: pimatic-raspbee : Light: Light 6 - null
20:16:44.668 [pimatic] info: Device discovered: pimatic-raspbee : Light: Light 7 - null
20:16:44.670 [pimatic] info: Device discovered: pimatic-raspbee : Light: Light 8 - null

**Comment by treban** [comment]
i will publish a development version with more debug output.

**Comment by treban** [comment]
Version 0.0.8 now has debug output during device discovery when debug mode is enabled in the plugin configuration. @mat1990dj can you post the device information.

**Comment by mat1990dj** [comment]
I'll get them yes, thanks

**Comment by mat1990dj** [comment]
'10': 
   { etag: 'ee240413806d8a31620184af756f2a11',
     hascolor: false,
     manufacturername: 'Unknown',
     modelid: null,
     name: 'Leds Cocina Coccion',
     state: { alert: 'none', on: false, reachable: true },
     swversion: null,
     type: 'Smart plug',
     uniqueid: '00:15:8d:00:02:4d:c9:d9-02' },

If I use CURL I can turn on, off and get state correctly
curl -s -H "Content-Type: application/json" -X PUT -d '{"on": true}' 192.168.1.123:8080/api/327452AA5E/lights/10/state

**Comment by treban** [comment]
thx for the output. next release will support the smart plug.

**Comment by treban** [comment]
please check version v0.0.10

**Comment by mat1990dj** [comment]
It works! Thank you very much!

**Comment by treban** [comment]
your welcome. Is the  aqara smart plug #21 still not working?

**Comment by mat1990dj** [comment]
Will test this evening and close if so, didnt have time this morning

**Comment by treban** [comment]
THX
