### ISSUE TITLE
Support for Innr Plug Power Consumption

### ISSUE THREAD

**Issue by 00lex** [treban/pimatic-raspbee#23]
Can see the consumption sensor on device discovery, but can't add it correctly. 
Power consumption is not official supported but from Innr but deconz read the value.

**Comment by treban** [comment]
please make a device discovery with activated debug option. 
you can then find a Json output of the device in the logs. 
Can you post  this here?

**Comment by 00lex** [comment]
Hi treban, thank you!
Here is want you need. 
It would be great if you implement "power"

`2018-12-04 09:22:32debug [pimatic-raspbee]: { e: 'changed',
  id: '4',
  r: 'sensors',
  state: 
   { current: 57,
     lastupdated: '2018-12-04T08:22:32',
     power: 6,
     voltage: 238 },
  t: 'event',
  uniqueid: '00:15:8d:00:01:fe:45:21-01-0b04' }`

btw. its the Innr plug SP120

**Comment by treban** [comment]
one question. the switch itself is displayed as a separate device and is already controllable?  
can you post the json from the switch also?

**Comment by 00lex** [comment]
thats what I get on discovery. the plug is represented two times:

<img width="496" alt="bildschirmfoto 2018-12-04 um 12 51 13" src="https://user-images.githubusercontent.com/39100562/49442618-50737b00-f7ca-11e8-93c1-18610d62599c.png">



the second one is instant controllable with id 11:

<img width="1669" alt="bildschirmfoto 2018-12-04 um 12 52 06" src="https://user-images.githubusercontent.com/39100562/49442661-7c8efc00-f7ca-11e8-81ab-62e29c539f65.png">




I guess the first is the consumption sensor. it comes without id. I tried a lot different things. multi sensor, different ids etc without luck.

<img width="1662" alt="bildschirmfoto 2018-12-04 um 12 51 47" src="https://user-images.githubusercontent.com/39100562/49442759-c2e45b00-f7ca-11e8-8b74-1eccf6574076.png">


here is the debug output: 

>   id: '4',
>   r: 'sensors',
>   state: 
>    { current: 0,
>      lastupdated: '2018-12-04T12:15:22',
>      power: 0,
>      voltage: 236 },
>   t: 'event',
>   uniqueid: '00:15:8d:00:01:fe:45:21-01-0b04' }
> 
>   '11': 
>    { etag: 'a32532bf56a8891c1c5f8dfd9d9c091d',
>      hascolor: false,
>      manufacturername: 'innr',
>      modelid: 'SP 120',
>      name: 'Saugerstrom',
>      state: { alert: 'none', bri: 254, on: false, reachable: true },
>      swversion: '2.0',
>      type: 'On/Off plug-in unit',
>      uniqueid: '00:15:8d:00:01:fe:45:21-01' } }
> 
>   '3': 
>    { config: { on: true, reachable: true },
>      ep: 1,
>      etag: 'aea9020409e10141ff9efb3e319fc0a4',
>      manufacturername: 'innr',
>      modelid: 'SP 120',
>      name: 'Consumption 3',
>      state: { consumption: 55, lastupdated: '2018-12-04T12:14:04' },
>      swversion: '2.0',
>      type: 'ZHAConsumption',
>      uniqueid: '00:15:8d:00:01:fe:45:21-01-0702' },
>      
>   '4': 
>    { config: { on: true, reachable: true },
>      ep: 1,
>      etag: '1e9232a53816c6a7856556a0a4ee1708',
>      manufacturername: 'innr',
>      modelid: 'SP 120',
>      name: 'Power 4',
>      state: 
>       { current: 0,
>         lastupdated: '2018-12-04T12:14:40',
>         power: 0,
>         voltage: 238 },
>      swversion: '2.0',
>      type: 'ZHAPower',
>      uniqueid: '00:15:8d:00:01:fe:45:21-01-0b04' },

**Comment by 00lex** [comment]
anything new?

**Comment by treban** [comment]
I've been on vacation the last few weeks.  But I have already started and can give you a first test version soon

**Comment by 00lex** [comment]
meanwhile I managed it with a shell sensor and got my values/ consumption with:

> curl -s -X GET http://127.0.0.1:8009/api/APIKEY/sensors/4 | grep -o -P -m 1 '(?<=power":).*?(?=,")'

enjoy your trip :)

**Comment by 00lex** [comment]
is this project dead?

**Comment by mwittig** [comment]
> is this project dead?

I don't think so as this plugin has gained a remarkable popularity in pimatic user community. Presumably, @treban is very busy these days and has no time to implement new features. I am sorry for the inconvenience.

**Comment by treban** [comment]
unfortunately i have very little time at the moment. but i promise to invest time in the plugin on the weekend. 
i have already rebuilt the plugin in some parts and therefore some more testing is necessary.

**Comment by 00lex** [comment]
thank you guys!!!!!! zigbee is meanwhile my main communication protocol in pimatic.
as I describe in the comment above I handle it. its just good to know you want to continue the work on this plugin. whenever.. :)

**Comment by treban** [comment]
hey @00lex, i have released a new version as beta.
could you test it?

i have rebuilt the devices. 
All devices except lights and switches are now of type RaspBeeMultiSensor.
the other types are still available for downward compatibility. 

Now you should be able to use two devices. 
- one for the switch 
- one for the sensor data

remove the the plugin folder. 
install the plugin manually

```
#inside pimatic app folder
npm install pimatic-raspbee@beta --production 
```

**Comment by 00lex** [comment]
can't start pimatic after install the beta. 
I tried everything. with --production and --unsafe-perm as described here https://forum.pimatic.org/topic/1114/updated-how-to-install-a-plugin-from-github-using-npm-or-git/2


I get 

```
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm WARN pimatic-app No description
npm WARN pimatic-app No repository field.
npm WARN pimatic-app No README data
npm WARN pimatic-app No license field.

+ pimatic-raspbee@0.0.11-beta.2
added 3 packages from 3 contributors and audited 4454 packages in 15.589s
found 138 vulnerabilities (33 low, 71 moderate, 34 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```


and here what I get from package-lock.json

```
    "pimatic-raspbee": {
      "version": "0.0.11-beta.2",
      "resolved": "https://registry.npmjs.org/pimatic-raspbee/-/pimatic-raspbee-0.0.11-beta.2.tgz",
      "integrity": "sha512-HjiwJoNc2K0THNngkF7hNvs85q1FWEAmTb/VGXPp1yQL8v0zBv/uiU4p35HMXmxs02br/tooRwp/wPgDmtjZCg==",
      "requires": {
        "request-promise": "^4.2.4",
        "ws": "^5.2.2"
      },
      "dependencies": {
        "request-promise": {
          "version": "4.2.4",
          "resolved": "https://registry.npmjs.org/request-promise/-/request-promise-4.2.4.tgz",
          "integrity": "sha512-8wgMrvE546PzbR5WbYxUQogUnUDfM0S7QIFZMID+J73vdFARkFy+HElj4T+MWYhpXwlLp0EQ8Zoj8xUA0he4Vg==",
          "requires": {
            "bluebird": "^3.5.0",
            "request-promise-core": "1.1.2",
            "stealthy-require": "^1.1.1",
            "tough-cookie": "^2.3.3"
          }
        },
        "ws": {
          "version": "5.2.2",
          "resolved": "https://registry.npmjs.org/ws/-/ws-5.2.2.tgz",
          "integrity": "sha512-jaHFD6PFv6UgoIVda6qZllptQsMlDEJkTQcybzzXDYM1XO9Y8em691FGMPmM46WGyLU4z9KMgQN+qrux/nhlHA==",
          "requires": {
            "async-limiter": "~1.0.0"
          }
        }
      }
    },
```


btw meanwhile im on buster and node v10.16.0

**Comment by treban** [comment]
I can reproduce it using a debian buster virtual machine with node v10.
Which npm version do you have installed?

**Comment by 00lex** [comment]
6.9.0

**Comment by treban** [comment]
try this: 

```
vagrant@buster:~/pimatic-app$ 

cd /home/pi/pimatic-app/node_modules
rm -rf pimatic-raspbee/
git clone https://github.com/treban/pimatic-raspbee.git
cd pimatic-raspbee/
git checkout 0.0.11
npm install

# restart pimatic
```

**Comment by 00lex** [comment]
btw. with this beta the pimatic interface won't come up. if I stop pimatic the process node is not in the list of top but the pid in the pimatic folder exists furthermore.

if I recover the old raspbee folder everything work. 

give me 10 minutes

**Comment by 00lex** [comment]
sry nope

```
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo git checkout 0.0.11
Branch '0.0.11' set up to track remote branch '0.0.11' from 'origin'.
Switched to a new branch '0.0.11'
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jayschema@0.3.2: this project is no longer maintained
npm WARN deprecated coffee-script@1.11.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN checkPermissions Missing write access to /home/pi/pimatic-app/node_modules/pimatic-raspbee
npm ERR! path /home/pi/pimatic-app/node_modules/pimatic-raspbee
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/pi/pimatic-app/node_modules/pimatic-raspbee'
npm ERR!  { [Error: EACCES: permission denied, access '/home/pi/pimatic-app/node_modules/pimatic-raspbee']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/home/pi/pimatic-app/node_modules/pimatic-raspbee\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/pi/pimatic-app/node_modules/pimatic-raspbee' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-07-03T21_19_32_039Z-debug.log
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ 

```

but why ?

> permission denied, access \'/home/pi/pimatic-app/node_modules/pimatic-raspbee\

**Comment by treban** [comment]
"permission denied" is strange. 

but i think you use sudo: 
after that, the normal user can't make a npm install
first line of your post:
```
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo git checkout 0.0.11
```

**Comment by treban** [comment]
#check the permission of the plugin-folder 
sudo chown -R pi:pi /home/pi/pimatic-app/node_modules/pimatic-raspbee
or 
#install dep with root
sudo npm install

**Comment by 00lex** [comment]
I try it again and give the whole pimatic-app folder 0777 permissions but after restart web interface won't come up and if I stop pimatic the pid exists furthermore. sry im not much of a help 

```
pi@home:~ $ sudo service pimatic stop
pi@home:~ $ sudo rm -rf /home/pi/pimatic-app/node_modules/pimatic-raspbee
pi@home:~ $ cd /home/pi/pimatic-app/node_modules
pi@home:~/pimatic-app/node_modules $ sudo git clone https://github.com/treban/pimatic-raspbee.git
Cloning into 'pimatic-raspbee'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 303 (delta 32), reused 38 (delta 17), pack-reused 237
Receiving objects: 100% (303/303), 121.23 KiB | 643.00 KiB/s, done.
Resolving deltas: 100% (181/181), done.
pi@home:~/pimatic-app/node_modules $ cd /home/pi/pimatic-app/node_modules/pimatic-raspbee
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo git checkout 0.0.11
Branch '0.0.11' set up to track remote branch '0.0.11' from 'origin'.
Switched to a new branch '0.0.11'
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jayschema@0.3.2: this project is no longer maintained
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated coffee-script@1.11.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

> typechecker@2.0.8 preinstall /home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/pimatic/node_modules/i18n-pimatic/node_modules/messageformat/node_modules/watchr/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/pimatic/node_modules/i18n-pimatic/node_modules/messageformat/node_modules/watchr/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> core-js@2.6.9 postinstall /home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/pimatic/node_modules/knex/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
added 920 packages from 1109 contributors in 121.513s
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ 
```

**Comment by treban** [comment]
that's really weird. 
i can reproduce the problem with the npm installation of the beta on my node10 dev.

although on the travis CI pipeline the plugin works with node 10.

if i use the git repo in my node10 dev environment everything works also.
 
i guess it has something to do with the npm installation.

**Comment by 00lex** [comment]
I started with a clean install of everything a few days ago and install node as here described https://pimatic.teamemo.com/Guide/Getting-Started

are you on buster too?

**Comment by treban** [comment]
my production is on node8 

i have created for testing a vagrant virutal box with buster 
and 
vagrant@buster:~/pimatic-app$ npm -v
6.9.0
vagrant@buster:~/pimatic-app$ nodejs -v
v10.16.0

i have changed some package dependencies. 
please try the npm install. 
in my environment it's working now 

inside pimatic app folder
sudo rm -rf node_modules/pimatic-raspbee/
sudo npm install --unsafe-perm pimatic-raspbee@beta

**Comment by 00lex** [comment]
> inside pimatic app folder
> sudo rm -rf node_modules/pimatic-raspbee/
> sudo npm install --unsafe-perm pimatic-raspbee@beta

that's what I did yesterday. wait a moment

**Comment by 00lex** [comment]
```
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo service pimatic stop
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo chown -R pi:pi /home/pi/pimatic-app/node_modules/pimatic-raspbee
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo service pimatic restart
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ sudo service pimatic stop
pi@home:~/pimatic-app/node_modules/pimatic-raspbee $ cd
pi@home:~ $ sudo rm -rf /home/pi/pimatic-app/node_modules/pimatic-raspbee
pi@home:~ $ cd /home/pi/pimatic-app/node_modules/
pi@home:~/pimatic-app/node_modules $ sudo npm install --unsafe-perm pimatic-raspbee@beta
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm WARN pimatic-app No description
npm WARN pimatic-app No repository field.
npm WARN pimatic-app No README data
npm WARN pimatic-app No license field.

+ pimatic-raspbee@0.0.11-beta.6
added 9 packages from 7 contributors, removed 5 packages and audited 4505 packages in 16.34s
found 138 vulnerabilities (33 low, 71 moderate, 34 high)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.9.0 → 6.10.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

```

**Comment by treban** [comment]
please run the install command in the pimatic-app folder 

pi@home:~/pimatic-app/node_modules $ sudo npm install --unsafe-perm pimatic-raspbee@beta
=> 
pi@home:~/pimatic-app/ $ sudo npm install --unsafe-perm pimatic-raspbee@beta

**Comment by 00lex** [comment]
```
pi@home:~/pimatic-app/node_modules $ sudo service pimatic stop
pi@home:~/pimatic-app/node_modules $ sudo rm -rf /home/pi/pimatic-app/node_modules/pimatic-raspbee
pi@home:~/pimatic-app/node_modules $ cd /home/pi/pimatic-app/
pi@home:~/pimatic-app $ sudo npm install --unsafe-perm pimatic-raspbee@beta
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
npm WARN pimatic-app No description
npm WARN pimatic-app No repository field.
npm WARN pimatic-app No README data
npm WARN pimatic-app No license field.

+ pimatic-raspbee@0.0.11-beta.6
added 4 packages from 3 contributors, removed 1 package, updated 4 packages and audited 4511 packages in 18.221s
found 138 vulnerabilities (33 low, 71 moderate, 34 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@home:~/pimatic-app $ 



```

**Comment by 00lex** [comment]
i install plugins form /pimatic-app/node_modules because mwittig sad that: 
https://forum.pimatic.org/topic/1114/updated-how-to-install-a-plugin-from-github-using-npm-or-git

**Comment by treban** [comment]
I don't get it. :(
i will check it tomorrow with an raspberrypi installation.

**Comment by 00lex** [comment]
no Problem :) see u

**Comment by 00lex** [comment]
btw: i have a 2nd usb drive attached and make a rsync of my main fs for testing and just reboot after edit the cmdline.txt.
its helpful in this cases :)

**Comment by treban** [comment]
> ```
> pi@home:~/pimatic-app/node_modules $ sudo service pimatic stop
> pi@home:~/pimatic-app/node_modules $ sudo rm -rf /home/pi/pimatic-app/node_modules/pimatic-raspbee
> pi@home:~/pimatic-app/node_modules $ cd /home/pi/pimatic-app/
> pi@home:~/pimatic-app $ sudo npm install --unsafe-perm pimatic-raspbee@beta
> npm WARN saveError ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
> npm WARN pimatic-app No description
> npm WARN pimatic-app No repository field.
> npm WARN pimatic-app No README data
> npm WARN pimatic-app No license field.
> 
> + pimatic-raspbee@0.0.11-beta.6
> added 4 packages from 3 contributors, removed 1 package, updated 4 packages and audited 4511 packages in 18.221s
> found 138 vulnerabilities (33 low, 71 moderate, 34 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
> pi@home:~/pimatic-app $ 
> ```

uh, the installation is successful here, although warnings are coming. 
can you start pimatic and post the log please

**Comment by 00lex** [comment]
```
00:34:40.955 [pimatic-hue-zll] Connected to bridge home, API version 1.16.0, software 2.5.65
00:34:40.959 [pimatic-raspbee] Connection establised
00:34:40.960 [pimatic-raspbee] Name home
00:34:40.960 [pimatic-raspbee] API 1.16.0
00:34:40.961 [pimatic-raspbee] Software Version 2.5.65
00:34:40.962 [pimatic-raspbee] API key valid
00:34:41.245 [pimatic-mobile-frontend] packing static assets
00:34:41.254 [pimatic-mobile-frontend] Error setting up assets in mobile-frontend: EACCES: permission denied, unlink '/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/public/assets/add-item-page-0b0bb3992c435ca7cb6dafa445d08276.js'
00:34:41.376 [pimatic-raspbee] Event receiver connected.
00:34:41.392 [pimatic] An uncaught exception occurred: TypeError: (intermediate value)(...).catch is not a function
00:34:41.392 [pimatic]>    at RaspBeeContactSensor.getInfos (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:394:61)
00:34:41.392 [pimatic]>    at RaspBeePlugin.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:380:10)
00:34:41.392 [pimatic]>    at RaspBeePlugin.emit (events.js:203:15)
00:34:41.392 [pimatic]>    at RaspBeeConnection.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:257:10)
00:34:41.392 [pimatic]>    at RaspBeeConnection.emit (events.js:198:13)
00:34:41.392 [pimatic]>    at WebSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:47:14)
00:34:41.392 [pimatic]>    at WebSocket.emit (events.js:198:13)
00:34:41.392 [pimatic]>    at WebSocket.setSocket (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/WebSocket.js:167:10)
00:34:41.392 [pimatic]>    at ClientRequest._req.on (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/WebSocket.js:715:10)
00:34:41.392 [pimatic]>    at ClientRequest.emit (events.js:198:13)
00:34:41.392 [pimatic]>    at Socket.socketOnData (_http_client.js:475:11)
00:34:41.392 [pimatic]>    at Socket.emit (events.js:198:13)
00:34:41.392 [pimatic]>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
00:34:41.392 [pimatic]>    at addChunk (_stream_readable.js:288:12)
00:34:41.392 [pimatic]>    at readableAddChunk (_stream_readable.js:269:11)
00:34:41.392 [pimatic]>    at Socket.Readable.push (_stream_readable.js:224:10)
00:34:41.392 [pimatic]>    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
00:34:41.392 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
00:34:41.398 [pimatic] exiting...
pi@home:~ $ 

```

**Comment by 00lex** [comment]
I need sleep. I come back this weekend to see what's going on. good night and thank you 

btw. i have a workaround with the shell sensor https://github.com/treban/pimatic-raspbee/issues/23#issuecomment-460671044

**Comment by treban** [comment]
ok, i will ckeck the error. 
but now the installation is working.

**Comment by 00lex** [comment]
I try a restart with a clean config and get a error which can do something with my system

```
pi@home:~ $ /home/pi/pimatic-app/node_modules/pimatic/pimatic.js
00:44:24.670 2019-07-04 Thursday
00:44:26.559 [pimatic] Starting pimatic version 0.9.50
00:44:26.563 [pimatic] Node.js version 10.16.0
00:44:26.563 [pimatic] OpenSSL version 1.1.1b
00:44:27.395 [pimatic, ppm] 2.15.12
00:44:27.411 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
00:44:27.632 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.15)
00:44:27.938 [pimatic-cron] the time is: Thu Jul 04 2019 00:44:27 GMT+0200 (Central European Summer Time)
00:44:28.127 [pimatic-mobile-frontend] packing static assets
00:44:28.151 [pimatic-mobile-frontend] Error setting up assets in mobile-frontend: EACCES: permission denied, unlink '/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/public/assets/add-item-page-0b0bb3992c435ca7cb6dafa445d08276.js'
00:44:28.178 [pimatic] Could not listen on port 8010. Error: listen EADDRINUSE: address already in use :::8010. Is a server already running?
00:44:28.182 [pimatic] exiting...
pi@home:~ $ 

```

i will try it with a 1:1 clone of my main system this weekend

**Comment by treban** [comment]
you can't have two instances of pimatic with the same port. 
your web port 8010 is already in use

**Comment by treban** [comment]
i have fixed the error 
you can try now v0.0.11-beta.7
with a new reinstall

**Comment by 00lex** [comment]
<img width="824" alt="Bildschirmfoto 2019-07-04 um 11 57 15" src="https://user-images.githubusercontent.com/39100562/60658162-efd91900-9e52-11e9-934d-5959dded22ac.png">


okay that works! 
but I just get power and don't know how to handle the mapping for consumption. 

<img width="1663" alt="Bildschirmfoto 2019-07-04 um 11 41 28" src="https://user-images.githubusercontent.com/39100562/60657276-5a895500-9e51-11e9-9a5c-f2056d0c8fab.png">

the other thing is setting up polling time would be nice.

and could your explain please in the final release what's that/ how that works

<img width="826" alt="Bildschirmfoto 2019-07-04 um 11 38 00" src="https://user-images.githubusercontent.com/39100562/60657597-e602e600-9e51-11e9-8d80-6e738c5dad05.png">


for the moment thank you very much for your ambitions! 
if you have any time passion again, take a look at this :) 
https://github.com/treban/pimatic-raspbee/issues/30

**Comment by treban** [comment]
The new readme is on the way -> [readme](https://github.com/treban/pimatic-raspbee/blob/0.0.11/README.md)
The Raspbee System represents the deconz api. 
* you can start a light or sensor dicovery without go to the deconz website.
* create a backup from the deconz db 
* send config button -> sends all configmaps from all mutidevices to the api. 

the new multidevice configures itself.  

which means: 
*  the first array represents all devices ids
* the second array all possible supported functions 

* the config map is automatically populated when configurable values are available. 
Here you don't have to do anything.

**Comment by treban** [comment]
in your case, 
sensorID 4 has current power and voltage 
sensorID 3 has consumtion 

the discovery process should fill the arrays automatically.

'3':
{ config: { on: true, reachable: true },
ep: 1,
etag: 'aea9020409e10141ff9efb3e319fc0a4',
manufacturername: 'innr',
modelid: 'SP 120',
name: 'Consumption 3',
state: { consumption: 55, lastupdated: '2018-12-04T12:14:04' },
swversion: '2.0',
type: 'ZHAConsumption',
uniqueid: '00:15:8d:00:01:fe:45:21-01-0702' },

'4':
{ config: { on: true, reachable: true },
ep: 1,
etag: '1e9232a53816c6a7856556a0a4ee1708',
manufacturername: 'innr',
modelid: 'SP 120',
name: 'Power 4',
state:
{ current: 0,
lastupdated: '2018-12-04T12:14:40',
power: 0,
voltage: 238 },
swversion: '2.0',
type: 'ZHAPower',
uniqueid: '00:15:8d:00:01:fe:45:21-01-0b04' },

**Comment by 00lex** [comment]
Great! Where did you save the backup? 
remember not everyone use deconz+pimatic on a pi or just run it with another user. 
its maybe I good idea to give them a option to set up the user from deconz for the backup feature
`/home/USER(?)/.local/share/dresden-elektronik/deCONZ/zll.db`

**Comment by treban** [comment]
currently the backups are stored in the pimatic-app folder. 
but i will include a configurable location.

does your device work now?

**Comment by 00lex** [comment]
yes but I`m back on my main system with the last official version of raspbee.

**Comment by treban** [comment]
Version 0.1.0 released and supports now all sensor properties
