### ISSUE TITLE
Off Dimlevel / Color restore doesnt work

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-raspbee#29]
Hello,
currently i have a strange issuee, thought this was working a time ago.
When i switch light off in Pimatic (was 70%) and switch on again it restores to 1%. 
Same is working in the phoscon app without problems.

Is this a configuration issue?

**Comment by treban** [comment]
the problem is reproducible. 
i will fix it in the next release.

**Comment by treban** [comment]
Version 0.1.0 released.
bug is fixed.
