### ISSUE TITLE
color support for pimatic-hap

### ISSUE THREAD

**Issue by 00lex** [treban/pimatic-raspbee#30]
hi treban, 
could you contact michbeck100 some time and ask him how to implement color support for his plugin? 
he can add now dimmer templates but then its just possible to switch bulbs and change brightness. 

https://github.com/michbeck100/pimatic-hap/issues/80#issuecomment-502968600

thank you

**Comment by treban** [comment]
i have reviewed it and small adjustments are necessary.

**Comment by treban** [comment]
@00lex 
Version 0.0.11-beta.10 supports now HAP Integration 

please install the beta and change the accessory to test it

https://github.com/michbeck100/pimatic-hap/blob/master/hap.coffee#L60
      'raspbee-dimmer': DimmerAccessory
      'raspbee-ct': DimmerAccessory
      'raspbee-rgb': **_HueLightAccessory_**

**Comment by 00lex** [comment]
it makes no difference in the latest beta. the results are the same. 
`'raspbee-rgb': HueLightAccessory    =    'raspbee-rgb': DimmerAccessory` in hap.coffee

- pure white lights (hue) are available in HomeKit and I can dim them.
- ambient white lights (hue) are available in HomeKit and I can dim them but can't change their temperature.
- color lights (hue) are not available in HomeKit. 

-----
I like what you want to do with sensors to collect them to a multi sensor but there is a big issue. 
they dont match the pimatic logic anymore. that means sensors are not sensors and I can't write rules like **if PIR is present** because there is no PIR in my setup anymore. instead I would need to realize everything with variables like **if $pir.motion = true**

i don't know if this helps but the variable of PIR in your last release for PIR was **$pir.presence**; in this beta its **$pir.motion**

**Comment by treban** [comment]
@00lex thanks for testing. 
i only rarely have iOS test hardware available. 
Last weekend a Tradfri RGB lamp was successfully integrated. I will check it again.

The build-in PredicateProvider uses the attribut name to select the devices. 
"state"
"presence"
"contact"

I will review the Multidevice to preserve this predefined attributes.  
Thx for the hint!

**Comment by 00lex** [comment]
Hey Everyone! If you are rich and like trebans plugin, send him testhardware!
iOS devices and everything with Zigbee radio

**Comment by treban** [comment]
Version 0.1.0 released: hap support with color is implemented and can be activated in the hap plugin.
i will rise a pull request for full integration

**Comment by 00lex** [comment]
https://github.com/michbeck100/pimatic-hap/issues/80#issuecomment-511399426
