### ISSUE TITLE
Motion Presence v1.0

### ISSUE THREAD

**Issue by 00lex** [treban/pimatic-raspbee#31]
Hi the multi sensor works with contact, motion, temp+humidity and gyro sensors, but there is a tiny issue with the motion sensor. 
the variable presence is listet in variables and it shows the correct state and I can set up rules like `PIR-Paradies2 is present`  but the presence state in the dashboard is broken. it doesnt react.  see my picture

dashboard:
<img width="497" alt="Bildschirmfoto 2019-07-15 um 14 56 11" src="https://user-images.githubusercontent.com/39100562/61217774-bafd7980-a710-11e9-8905-b8a5c7b20a1e.png">

variable:
<img width="505" alt="Bildschirmfoto 2019-07-15 um 14 57 37" src="https://user-images.githubusercontent.com/39100562/61217868-f1d38f80-a710-11e9-84ee-05e8e9d7e4d5.png">

**Comment by treban** [comment]
fixed with 0.1.1

**Comment by 00lex** [comment]
YES! Thank you for the quick fix
