### ISSUE TITLE
Device Scan not working ?

### ISSUE THREAD

**Issue by treban** [treban/pimatic-raspbee#33]
```
17:40:23.578 [pimatic-raspbee] { e: 'added',
17:40:23.578 [pimatic-raspbee]>  id: '7',
17:40:23.578 [pimatic-raspbee]>  r: 'lights',
17:40:23.578 [pimatic-raspbee]>  t: 'event',
17:40:23.578 [pimatic-raspbee]>  uniqueid: '84:18:26:00:00:0e:7c:34-03' }
17:40:23.578 [pimatic-raspbee] new device paired!
17:40:23.581 [pimatic] An uncaught exception occurred: TypeError: Cannot read property 'name' of undefined
17:40:23.581 [pimatic]>    at RaspBeeSystem.parseEvent (/opt/pimatic-docker/node_modules/pimatic-raspbee/raspbee.coffee:1564:44)
```

**Comment by treban** [comment]
I'm working on it.

**Comment by 00lex** [comment]
Whats going on? in the course of the extensive changes of raspbee I re-add all my devices without issues. which deconz version do you use? I am on 2.05.65 (stable/ native install)

**Comment by treban** [comment]
2.05.66

**Comment by 00lex** [comment]
a moth ago I try 2.05.66 and have another issues and downgrade to 2.05.65.
has nothing to do with raspbee I think.  
I can check what happens with 2.05.66 with the new raspbee in my setup. 15m..

**Comment by 00lex** [comment]
this was my problem with 2.05.66 https://github.com/markbergsma/pimatic-hue-zll/issues/21
but thanks to you and the new raspbee version, hue-zll is obsolet 👍 

ok now I reboot into my test setup, change deconz to testing and update to 2.05.66. 
- discovery works
- adding bulbs (hue) works
- adding body motion sensor (aqara) works

**Comment by treban** [comment]
strange, i added an osram plug. I will check if another device has the same problem.

**Comment by 00lex** [comment]
- adding Innr Plug (switch+consuption) works
i have no Osram plug. 

is your problem maybe a docker thing? Is there meanwhile a stable raspbian buster version?

**Comment by treban** [comment]
I'll run some tests and catch the error if necessary.
i am currently working on the hue/sat topic :)

**Comment by 00lex** [comment]
no stress ;)

**Comment by treban** [comment]
fixed
