### ISSUE TITLE
Activating Group Szene results in "error [pimatic]: devices is not defined"

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-raspbee#35]
When a rule with action "activate group scene Essen" is created, a error Message is displayed:
"error [pimatic]: devices is not defined"

Rule elements are suggested by pimatic auto-suggestion

**Comment by treban** [comment]
release 0.1.4 published with the fix

**Comment by scobby** [comment]
Wow, that was fast! Thx a lot! 

Von meinem Smartphone 
gesendet
