### ISSUE TITLE
device XYZ is not modifiable. Device is set to off

### ISSUE THREAD

**Issue by 00lex** [treban/pimatic-raspbee#36]
Hi Kosta! 

Maybe you remember my comment: 
https://github.com/treban/pimatic-raspbee/issues/17#issuecomment-512740901

In rules, I can fix this by adding a delay for the 2nd part "change color", but sometimes and I don't know why, pimatic throw errors anyway. 

maybe you can change the behavior of the raspbee plugin how to interact with turned off lights when you change the color first.

you can reproduce this easily by changing color OR color temp of a turned off light and the you get: 
<img width="488" alt="Bildschirmfoto 2019-08-18 um 12 32 55" src="https://user-images.githubusercontent.com/39100562/63223357-57091d80-c1b4-11e9-916c-15ac45962700.png">

if you try this in deconz, deconz will turn on the light automatically and change the color. 
this already worked with the hue-zll plugin. 

yes, I think we can live with that behavior, but if you know what's wrong and its not a big deal, you can fix this in a future update.

thank you

**Comment by treban** [comment]
hi, 
no problem, i can implement it.
the deconz api does not allow changes when the lamp is turned off. 
i don't know how other APIs manage this. but the simplest thing is,
that switched off lamps go on when you change the color values.

**Comment by 00lex** [comment]
> the deconz api does not allow changes when the lamp is turned off.
> i don't know how other APIs manage this.

i don't know. sure? you could look what hack hue-zll use to bypass this

**Comment by treban** [comment]
the deconz api returns a forbidden response. 
i have looked. the hue plugin also simply sends the two requests one behind the other. 

i will add this to the next release.

**Comment by treban** [comment]
@00lex you can close the question ;) 
https://github.com/markbergsma/pimatic-hue-zll/blob/master/hue-zll.coffee#L542

**Comment by 00lex** [comment]
muchas gracias!

**Comment by treban** [comment]
de nada

**Comment by 00lex** [comment]
> https://github.com/markbergsma/pimatic-hue-zll/blob/master/hue-zll.coffee#L542

hey kosta, I don't understand this, but i was not inactive.
I ask someone how he fix this, but read yourself: 
https://github.com/ebaauw/homebridge-hue/issues/515
its rather far-fetched because of homekit, but maybe you'll see the light. 
sry if im a little overengaged. do what you think is right. you are the cook :)

**Comment by treban** [comment]
version 0.1.5 published

now the plugin switch the lights on when parameters are modified
(with the same request)

**Comment by 00lex** [comment]
works! thank you again
