### ISSUE TITLE
Sensors are not shown properly 

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-raspbee#37]
On iPhone X in Chrome and Safari 
![DF6EE4BF-6AEF-4C6D-8008-39265CEC313C](https://user-images.githubusercontent.com/9264361/63532911-05da9000-c50c-11e9-807a-ba785f6f21e1.png)
![C9E71B62-CB4D-4B53-9B6E-E4E24F5FA6DC](https://user-images.githubusercontent.com/9264361/63532912-05da9000-c50c-11e9-908f-d6a151e341fb.png)

**Comment by 00lex** [comment]
its not a raspbee bug and maybe not a pimatic bug. 
you are using pimatic as an webapp on your home screen. 
I know similar bugs. rotate your phone 90° and back :)
log out and log in fix this.

or you could try to make your device more compact: 
![IMG_1269](https://user-images.githubusercontent.com/39100562/63552055-03416000-c537-11e9-8051-c0c0081393e0.jpg)

**Comment by treban** [comment]
I was able to reproduce the problem with chrome. 
when the attribute list is long and a presence ring is displayed. this display problem occurs. 

with the new css value in the frontend-plugin the problem is solved. 
the fix is comming. https://github.com/pimatic/pimatic-mobile-frontend/pull/28
