### ISSUE TITLE
Thermostat (Eurotronic) resource types

### ISSUE THREAD

**Issue by 00lex** [treban/pimatic-raspbee#42]
hi! me again :)

can you add some time resource types "valve" and "heatsetpoint"?

valve is **just a** read **value** (no angle) 0-255 for position. 
heatsetpoint is a value from 500-3000 (5,00°C-30,00°C).

it would be nice if you could divide heatsetpoint by 100 and if its possible to create a input. 

my workaround for valve is shell sensor: 
`curl -s -X GET http://127.0.0.1:8009/api/A7D65FD/sensors/41 | grep -o -P '(?<=valve":).*?(?=})'`
or in %
`echo $(curl -s -X GET http://127.0.0.1:8009/api/A7D65FD443/sensors/41 | grep -o -P '(?<=valve":).*?(?=})')*100/255 | bc -l`

for heatsetpoint I use a dummyheatingthermostat for input, a rule to write a variable (dummyheatingthermostat °C * 100), a 2nd rule to write the heatsetpoint
`curl -s -H 'Content-Type: application/json' -X PUT -d '\{\"heatsetpoint\": $tempvar\}' http://127.0.0.1:8009/api/A7D65FD/sensors/41/config`
and two additional rules to prevent value inputs <5 and >30.

this is btw the output from the thermostat:
```
curl -s -X GET http://127.0.0.1:8009/api/A7D65FD/sensors/41
{"config":{"battery":75,"displayflipped":null,"heatsetpoint":500,"locked":null,"mode":"auto","offset":0,"on":true,"reachable":true},"ep":1,"etag":"459b89fdc44f400b62ac7e6a92adef4f","manufacturername":"Eurotronic","modelid":"SPZB0001","name":"SPZB0001","state":{"lastupdated":"2019-10-18T06:11:52","on":false,"temperature":1594,"valve":0},"swversion":"20190408","type":"ZHAThermostat","uniqueid":"00:15:8d:00:01:92:dc:21-01-0201"}
```

thank you!

OT: I can't 100% recommend this thermostat. the hardware seems to work well. but the integration in deconz is not finished. you need the desktop gui to add the device and after that its not shown in the webapp. the rest-api is a mandatory. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098

pimatic-raspbee just shows the temperature: 
<img width="1664" alt="Bildschirmfoto 2019-10-18 um 08 48 59" src="https://user-images.githubusercontent.com/39100562/67071994-3e04f480-f184-11e9-9e37-6d1e4d9c38ba.png">

**Comment by treban** [comment]
Yes I can create a thermostat device for that.

**Comment by treban** [comment]
duplicate  #45
