### ISSUE TITLE
Some errors with deconz version 2.5.78

### ISSUE THREAD

**Issue by treban** [treban/pimatic-raspbee#47]
i get some errors with the new version of deconz. 

[pimatic] error: An uncaught exception occurred: TypeError: Cannot read property 'ct' of undefined
and I often get a reconnect. 

The plugin needs an modification for the new version. I will release this soon.

**Comment by fennsen64** [comment]
see #49. seems to be the same root course. When will you update the adapter? THX in advice

**Comment by 00lex** [comment]
<img width="1680" alt="Bildschirmfoto 2020-07-16 um 15 27 58" src="https://user-images.githubusercontent.com/39100562/87676666-2c836400-c779-11ea-851c-72e2ffc28418.png">

when 2.5.78 beta was out, I thought it has something to do with deconz. 
now they decide 2.5.78 is stable and I found this / your post. 

thank you for fixing it! I will go to 2.5.77 back again till then

**Comment by 00lex** [comment]
@treban are u on vacation again? :)

**Comment by treban** [comment]
published new hotfix release 0.1.6

**Comment by mat1990dj** [comment]
In my case there is still some error preventing to start pimatic

09:38:16.917 [pimatic] info: Loading plugin: "pimatic-raspbee" (0.1.6)
coffee-cache: compiling coffee-script file "raspbee.coffee"...Done
coffee-cache: compiling coffee-script file "color.coffee"...Done
coffee-cache: compiling coffee-script file "raspbee-connector.coffee"...Done
coffee-cache: compiling coffee-script file "action.coffee"...Done
coffee-cache: compiling coffee-script file "predicate.coffee"...Done
coffee-cache: compiling coffee-script file "raspbee-config-schema.coffee"...Done

09:39:14.728 [pimatic-raspbee] info: Connection establised
09:39:14.730 [pimatic-raspbee] info: Name rpiz
09:39:14.732 [pimatic-raspbee] info: API 1.16.0
09:39:14.734 [pimatic-raspbee] info: Software Version 2.5.79
09:39:14.736 [pimatic-raspbee] info: API key valid
09:39:23.144 [pimatic-raspbee] info: Event receiver connected.
09:39:23.234 [pimatic-raspbee] debug: new message received
09:39:23.250 [pimatic-raspbee] debug: { attr: 
09:39:23.250 [pimatic-raspbee] debug:>   { lastannounced: null,
09:39:23.250 [pimatic-raspbee] debug:>     lastseen: '2020-07-21T07:39:16Z',
09:39:23.250 [pimatic-raspbee] debug:>     manufacturername: 'innr',
09:39:23.250 [pimatic-raspbee] debug:>     modelid: 'RB 265',
09:39:23.250 [pimatic-raspbee] debug:>     name: 'Luz Salon',
09:39:23.250 [pimatic-raspbee] debug:>     swversion: '2.0',
09:39:23.250 [pimatic-raspbee] debug:>     type: 'Dimmable light',
09:39:23.250 [pimatic-raspbee] debug:>     uniqueid: '00:15:8d:00:02:f6:f2:4c-01' },
09:39:23.250 [pimatic-raspbee] debug:>  e: 'changed',
09:39:23.250 [pimatic-raspbee] debug:>  id: '9',
09:39:23.250 [pimatic-raspbee] debug:>  r: 'lights',
09:39:23.250 [pimatic-raspbee] debug:>  t: 'event',
09:39:23.250 [pimatic-raspbee] debug:>  uniqueid: '00:15:8d:00:02:f6:f2:4c-01' }
09:39:23.273 [pimatic] error: An uncaught exception occurred: TypeError: Cannot read property 'bri' of undefined
09:39:23.273 [pimatic] error:>    at RaspBeeDimmer.parseEvent (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:1013:10)
09:39:23.273 [pimatic] error:>    at RaspBeePlugin.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:997:12)
09:39:23.273 [pimatic] error:>    at emitOne (events.js:121:20)
09:39:23.273 [pimatic] error:>    at RaspBeePlugin.emit (events.js:211:7)
09:39:23.273 [pimatic] error:>    at RaspBeeConnection.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:252:10)
09:39:23.273 [pimatic] error:>    at emitOne (events.js:116:13)
09:39:23.273 [pimatic] error:>    at RaspBeeConnection.emit (events.js:211:7)
09:39:23.273 [pimatic] error:>    at WebSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:65:14)
09:39:23.273 [pimatic] error:>    at emitOne (events.js:116:13)
09:39:23.273 [pimatic] error:>    at WebSocket.emit (events.js:211:7)
09:39:23.273 [pimatic] error:>    at Receiver.receiverOnMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:720:20)
09:39:23.273 [pimatic] error:>    at emitOne (events.js:116:13)
09:39:23.273 [pimatic] error:>    at Receiver.emit (events.js:211:7)
09:39:23.273 [pimatic] error:>    at Receiver.dataMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:414:14)
09:39:23.273 [pimatic] error:>    at Receiver.getData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:346:17)
09:39:23.273 [pimatic] error:>    at Receiver.startLoop (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:133:22)
09:39:23.273 [pimatic] error:>    at Receiver._write (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:69:10)
09:39:23.273 [pimatic] error:>    at doWrite (_stream_writable.js:396:12)
09:39:23.273 [pimatic] error:>    at writeOrBuffer (_stream_writable.js:382:5)
09:39:23.273 [pimatic] error:>    at Receiver.Writable.write (_stream_writable.js:290:11)
09:39:23.273 [pimatic] error:>    at Socket.socketOnData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:795:35)
09:39:23.273 [pimatic] error:>    at emitOne (events.js:116:13)
09:39:23.273 [pimatic] error:>    at Socket.emit (events.js:211:7)
09:39:23.273 [pimatic] error:>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
09:39:23.273 [pimatic] error:>    at Socket.Readable.read (_stream_readable.js:475:10)
09:39:23.273 [pimatic] error:>    at flow (_stream_readable.js:846:34)
09:39:23.273 [pimatic] error:>    at resume_ (_stream_readable.js:828:3)
09:39:23.273 [pimatic] error:>    at _combinedTickCallback (internal/process/next_tick.js:139:11)
09:39:23.273 [pimatic] error:>    at process._tickCallback (internal/process/next_tick.js:181:9)
09:39:23.273 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!

**Comment by 00lex** [comment]
For me 0.1.6 works with 2.5.78 without errors after 10min runtime. 
if I don't come back, everything is okay. 

thank you!

**Comment by mat1990dj** [comment]
I'm on 2.5.79  😫

**Comment by 00lex** [comment]
im on my test partition. will try 2.5.79..

**Comment by mat1990dj** [comment]
Maybe it's something related to the specific device?
It's a bulb and via the rest API on /lights I get:
"9": {
        "etag": "7513046fd04aee4bcb5912a05417a6ed",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2020-07-21T08:11:23Z",
        "manufacturername": "innr",
        "modelid": "RB 265",
        "name": "Luz Salon",
        "state": {
            "alert": "none",
            "bri": 254,
            "on": false,
            "reachable": true
        },
        "swversion": "2.0",
        "type": "Dimmable light",
        "uniqueid": "00:15:8d:00:02:f6:f2:4c-01"
    }

It seems that "bri" is there.

**Comment by 00lex** [comment]
yes, with deconz BETA 2.5.79 pimatic-raspbee produce errors 


<img width="1680" alt="Bildschirmfoto 2020-07-21 um 10 12 32" src="https://user-images.githubusercontent.com/39100562/88029893-d9bff880-cb3a-11ea-879a-17a92f16e6b8.png">


> error [pimatic]: An uncaught exception occurred: TypeError: Cannot read property 'bri' of undefined
>     at RaspBeeDimmer.parseEvent (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:1013:10)
>     at RaspBeePlugin.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:997:12)
>     at RaspBeePlugin.emit (events.js:203:15)
>     at RaspBeeConnection.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:252:10)
>     at RaspBeeConnection.emit (events.js:198:13)
>     at WebSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:65:14)
>     at WebSocket.emit (events.js:198:13)
>     at Receiver.receiverOnMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:720:20)
>     at Receiver.emit (events.js:198:13)
>     at Receiver.dataMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:414:14)
>     at Receiver.getData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:346:17)
>     at Receiver.startLoop (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:133:22)
>     at Receiver._write (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:69:10)
>     at doWrite (_stream_writable.js:415:12)
>     at writeOrBuffer (_stream_writable.js:399:5)
>     at Receiver.Writable.write (_stream_writable.js:299:11)
>     at Socket.socketOnData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:795:35)
>     at Socket.emit (events.js:198:13)
>     at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
>     at addChunk (_stream_readable.js:288:12)
>     at readableAddChunk (_stream_readable.js:269:11)
>     at Socket.Readable.push (_stream_readable.js:224:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
>  This is most probably a bug in pimatic or in a module, please report it!
> 10:12:11error [pimatic-raspbee]: Error: Light with ID: 65519 not found
>     at /home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:116:33
>     at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:725:18)
>     at _drainQueueStep (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:15:14)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> 10:12:11error [pimatic-raspbee]: websocket keep alive error, try to reconnect
> 10:11:13error [pimatic]: An uncaught exception occurred: TypeError: Cannot read property 'bri' of undefined
>     at RaspBeeDimmer.parseEvent (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:1013:10)
>     at RaspBeePlugin.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:997:12)
>     at RaspBeePlugin.emit (events.js:203:15)
>     at RaspBeeConnection.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:252:10)
>     at RaspBeeConnection.emit (events.js:198:13)
>     at WebSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:65:14)
>     at WebSocket.emit (events.js:198:13)
>     at Receiver.receiverOnMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:720:20)
>     at Receiver.emit (events.js:198:13)
>     at Receiver.dataMessage (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:414:14)
>     at Receiver.getData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:346:17)
>     at Receiver.startLoop (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:133:22)
>     at Receiver._write (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:69:10)
>     at doWrite (_stream_writable.js:415:12)
>     at writeOrBuffer (_stream_writable.js:399:5)
>     at Receiver.Writable.write (_stream_writable.js:299:11)
>     at Socket.socketOnData (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:795:35)
>     at Socket.emit (events.js:198:13)
>     at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
>     at addChunk (_stream_readable.js:288:12)
>     at readableAddChunk (_stream_readable.js:269:11)
>     at Socket.Readable.push (_stream_readable.js:224:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
>  This is most probably a bug in pimatic or in a module, please report it!
> 10:11:11error [pimatic-raspbee]: Error: Light with ID: 65519 not found
>     at /home/pi/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:116:33
>     at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/promise.js:725:18)
>     at _drainQueueStep (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic-raspbee/node_modules/bluebird/js/release/async.js:15:14)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> 10:11:11error [pimatic-raspbee]: websocket keep alive error, try to reconnect

**Comment by treban** [comment]
Hotfix 0.1.7 released :)

the 0.1.6 was empty.
had me tangled with the branches.

**Comment by mat1990dj** [comment]
It works. Thank you very much!

**Comment by 00lex** [comment]
> Hotfix 0.1.7 released :)
> 
> the 0.1.6 was empty.
> had me tangled with the branches.

that's crazy. 0.1.6 runs with 2.5.78 without errors. with 2.5.79 not. 
anyway 0.1.7 runs fine with both versions

**Comment by fennsen64** [comment]
Hi, after the 0.1.7 worked with deconz 2.5.77 / 2.5.78, I tried to use updated deconz Version 2.5.81 because there are some major issues fixed.
Unfortunaly, I get the same error again as before the fix with 0.1.7:

`14:16:11.653 [pimatic] error: An uncaught exception occurred: TypeError: Cannot read property 'on' of undefined
14:16:11.653 [pimatic] error:>    at RaspBeeSwitch.parseEvent (/usr/local/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:934:29)
14:16:11.653 [pimatic] error:>    at RaspBeePlugin.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:918:12)
14:16:11.653 [pimatic] error:>    at RaspBeePlugin.emit (events.js:203:15)
14:16:11.653 [pimatic] error:>    at RaspBeeConnection.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-raspbee/raspbee.coffee:252:10)
14:16:11.653 [pimatic] error:>    at RaspBeeConnection.emit (events.js:198:13)
14:16:11.653 [pimatic] error:>    at WebSocket.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-raspbee/raspbee-connector.coffee:65:14)
14:16:11.653 [pimatic] error:>    at WebSocket.emit (events.js:198:13)
14:16:11.653 [pimatic] error:>    at Receiver.receiverOnMessage (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:720:20)
14:16:11.653 [pimatic] error:>    at Receiver.emit (events.js:198:13)
14:16:11.653 [pimatic] error:>    at Receiver.dataMessage (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:414:14)
14:16:11.653 [pimatic] error:>    at Receiver.getData (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:346:17)
14:16:11.653 [pimatic] error:>    at Receiver.startLoop (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:133:22)
14:16:11.653 [pimatic] error:>    at Receiver._write (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/receiver.js:69:10)
14:16:11.653 [pimatic] error:>    at doWrite (_stream_writable.js:415:12)
14:16:11.653 [pimatic] error:>    at writeOrBuffer (_stream_writable.js:399:5)
14:16:11.653 [pimatic] error:>    at Receiver.Writable.write (_stream_writable.js:299:11)
14:16:11.653 [pimatic] error:>    at Socket.socketOnData (/usr/local/pimatic-app/node_modules/pimatic-raspbee/node_modules/ws/lib/websocket.js:795:35)
14:16:11.653 [pimatic] error:>    at Socket.emit (events.js:198:13)
14:16:11.653 [pimatic] error:>    at Socket.emit (/usr/local/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
14:16:11.653 [pimatic] error:>    at addChunk (_stream_readable.js:288:12)
14:16:11.653 [pimatic] error:>    at readableAddChunk (_stream_readable.js:269:11)
14:16:11.653 [pimatic] error:>    at Socket.Readable.push (_stream_readable.js:224:10)
14:16:11.653 [pimatic] error:>    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
14:16:11.653 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
14:16:11.659 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!`
