### ISSUE TITLE
Xiaomi/aqara motion sensor with lux not working

### ISSUE THREAD

**Issue by sweebee** [treban/pimatic-raspbee#8]
Device discovery doesn’t find the right class (empty), and when settings to RaspbeeMotionSensor it doesn’t work.

**Comment by mwittig** [comment]
@sweebee Maybe you can provide some pimatic debug output here showing the list of zigbee devices. If you  don't have it in the pimatic log, you can add a line to the scan function as shown below (will be output if debug enabled for the plugin and device discovery is performed).

https://github.com/mwittig/pimatic-raspbee/blob/dd280f48addab726e36495fceccc97d918cf6c96/raspbee.coffee#L72

**Comment by sweebee** [comment]
I already found what it was. the plugin shows 2 devices, 1 is the motion device and the other is de light sensor.

I'm currently implementing this device.

**Comment by mwittig** [comment]
@sweebee I think this needs some thought to possibly have multiple ZigBee devices automatically combined into a single pimatic device. See also my comment on #4 

I think it would be nice to have MultiSensor, at least, which autimatically exposes the attributes for the different sensor types combined.

**Comment by sweebee** [comment]
I Agree, we need a smart way to detect this. Maybe we can compare some stuff in the connector/event emitter and combine the data.
